# Generated by Django 5.2 on 2025-04-06 18:37

import first_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='dars_n',
            new_name='nomi',
        ),
        migrations.RenameField(
            model_name='salom',
            old_name='name',
            new_name='ism',
        ),
        migrations.AlterField(
            model_name='jamoa',
            name='img',
            field=models.ImageField(upload_to='img/', validators=[first_app.utils.rasm_ulchami]),
        ),
    ]
